### ISSUE TITLE
Reload raises exception on deleted object

### ISSUE THREAD

**Issue by voltechs** [remiprev/her#501] opened 2018-04-25 23:20 UTC
After deleting an object, calling reload on the object breaks because the API returns `nil`

https://github.com/remiprev/her/blob/97fe497a1757dadab11ebd267f0e9e694c21e23a/lib/her/model/orm.rb#L135-L150

**Comment by zacharywelch** [comment] 2018-04-26 17:37
Confirmed this is an issue. Here's a failing spec

```ruby
describe "calling reload on deleted resource"
  before do
    Her::API.setup url: "https://api.example.com" do |builder|
      builder.adapter :test do |stub|
        stub.delete("/users/1") { [200, {}, { id: 1, name: "Tobias" }.to_json] }
        stub.get("/users/1") { [404, {}, { errors: ["Resource not found"] }.to_json] }
      end
    end

    spawn_model "User"
  end

  it "handles reload on a deleted resource" do
    @user = User.destroy_existing(1)
    expect(@user.reload).to be_nil
  end
end
```

This could also occur if you're holding onto a resource that's been deleted by someone else
```ruby
@user = User.find(1) 
# in the meantime someone else deletes the resource
@user.reload #=> :(
```

One solution would be to mark the resource as destroyed and return `self`

```ruby
@user = User.destroy_existing(1) <User(users/1) id=1 name="Tobias Fünke"> 
@user.destroyed? #=> true
@user.reload #=> <User(users/1) id=1 name="Tobias Fünke">
@user.destroyed? #=> true
```

However the idea behind `reload` is the object is reinitialized with the result of `find`, which in this case is `nil`. My preference would be for `Her` to behave like `ActiveRecord` raise a `ResourceNotFound` in the event `find` returns `nil` or the status is `404`. 

```ruby
# calling find on non-existing resource
@user = User.find(-1) #=> raises Her::Errors::ResourceNotFound

# calling reload on deleted resource
@user = User.find(1)
@user.destroy #=> DELETE /users/1
@user.destroyed? #=> true
@user.reload #=> raises Her::Errors::ResourceNotFound

# example catching error
def user
  @user ||= User.find(-1)
rescue Her::Errors::ResourceNotFound
  NullUser.new
end
```

To add this behavior we'd be looking at a breaking change to the `find` api. Thoughts?

@voltechs in the meantime are you able to rescue the nil exception or provide a workaround?

Thanks!

**Comment by zacharywelch** [comment] 2018-05-01 15:44
@voltechs your best bet would be to use Faraday's [RaiseError](https://github.com/lostisland/faraday/blob/master/lib/faraday/response/raise_error.rb) middleware and catch the exception when the resource is not found. This also satisfies the `find` use case [above](https://github.com/remiprev/her/issues/501#issuecomment-384725995) 😎 

Gonna close this since we have a solution but feel free to reopen if you're still having issues. Thanks!

**Closed by zacharywelch** 2018-05-01 15:44 UTC
