### ISSUE TITLE
getting an association is returning Her::Model::Associations:: object rather than collection

### ISSUE THREAD

**Issue by justinsoong** [remiprev/her#214] opened 2014-02-11 22:36 UTC
```
class Company
  include Her::Model

  primary_key :company_number
  has_many :announcements
end

class MAP::Announcement
  include Her::Model

  primary_key :announcement_id
  belongs_to :company
end
```

```
company = Company.find('ABC')
company.announcements
=> #<Her::Model::Associations::HasManyAssociation:0x00000103e3f018 ...>
```

**Comment by zacharywelch** [comment] 2018-05-01 15:51
Gonna close this as a duplicate of #135. Thanks @chewi!

**Closed by zacharywelch** 2018-05-01 15:51 UTC
