### ISSUE TITLE
Find or Create by ID

### ISSUE THREAD

**Issue by sqlninja** [remiprev/her#527] opened 2019-06-18 16:25 UTC
So I have a "micro" twitter system I maintain, where we store profiles, tweets, favorites, and followers for users in our db.
We store them because we crunch a lot of data together and it's easier than calling the real twitter API every time.

I've noticed when trying to do a find_or_create_by on profiles that if I use the id for the profile it always attempts an update because of the ORM#new? method checking for an id.

I have a search that allows users to search for other Twitter users, and I then attempt to save the new twitter profile using the id, this ensures if a screen_name changes we still get who we were hoping for.

Any insight on the best way to handle this?

**Comment by sqlninja** [comment] 2019-06-18 16:26
I feel this can stem from this issue as well: https://github.com/remiprev/her/issues/494

**Comment by zacharywelch** [comment] 2019-07-24 01:33
Hi @sqlninja as you point out, this is a side effect of `new?` not knowing if the resource exists or not. The only workaround that comes to mind is calling [save_existing](https://github.com/remiprev/her/tree/fd192875777f11135ec2188a4a9b8346226b9561#activerecord-like-methods) when `find` or `find_by` returns nil. Let us know if that helps. Meanwhile I'm going to close this as a duplicate of #494.

**Closed by zacharywelch** 2019-07-24 01:33 UTC
