### ISSUE TITLE
Associations using the class_name option silently fail if the class fails to load

### ISSUE THREAD

**Issue by blazingkin** [remiprev/her#474] opened 2017-11-29 02:52 UTC
Example of the issue
======
Suppose you have a her model that looks something like this
```
class Foo
    include Her::Model
    has_many :bars, class_name: 'Bar'
end
```
where 'Bar' is some other model.

Description of the issue
======
This model actually has a really subtle bug that is hard to notice.

Because the constant Bar is never referenced in this class, [rails never autoloads it](http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoloading-algorithms). This means that if Foo is loaded before Bar, the reference to Bar is undefined and an error should be thrown.

Except - Her uses the following to find the class from the 'class_name' opt
` her_sibling_class(name) || name.constantize rescue nil`
i.e. if the class can't be found, it returns nil.

So now, instead of the code blowing up, if Foo loads before Bar the model behaves as if it was declared this way -
```
class Foo
    include Her::Model
    has_many :bars
end
```
Which is clearly not what was intended.

Why it matters
======
My team has had tests failing on our build server apparently randomly for about 5 weeks due to this issue. We could not recreate the failure locally, and the error message made no sense.

The error that actually gets thrown is that bars will be of type HashWithIndifferentAccess rather than the intended type of Bar. The error will certainly be thrown later in the program, so it will be difficult to trace back to the root cause.

This is compounded by the fact that since this is a load order bug, it will not happen all the time and will happen differently in different environments.

The fix
======
The correct model, without the bug is
```
require 'bar'
class Foo
    include Her::Model
    has_many :bars, class_name: 'Bar'
end
```

A stupidly simple fix.

What Her can do
======
Rather than just silently continuing if the class cannot be loaded, throw an error message. It would have saved us a lot of time and effort.

**Comment by edtjones** [comment] 2017-11-29 07:34
Thanks for the report @blazingkin - we could check Bar is defined when defining the association I guess. Fancy putting together a PR?

**Comment by blazingkin** [comment] 2017-11-29 20:07
Yeah, I can do that.

**Comment by edtjones** [comment] 2017-11-29 20:18
Perfect - thanks in advance!

**Comment by zacharywelch** [comment] 2018-02-27 22:36
Gonna go ahead and close this since #480 was merged 😺

**Closed by zacharywelch** 2018-02-27 22:36 UTC

**Comment by thornfoot** [comment] 2018-03-02 15:00
What is the best-practice for avoiding this exception in the first place?

**Comment by blazingkin** [comment] 2018-03-02 17:36
Hi @thornfoot!
Hope this didn't break anything in CAR

The simplest way to fix the error is to `require 'bar'`

That may not be the easiest thing to remember, so perhaps a better solution is to adopt a code pattern like 

`has_many :bars, class_name: Bar.class.name`

Rails should then autoload the Bar class.

The best solution would be to change the parameter that Her takes so that it is something that rails will autoload. (e.g. `has_many :bars, class: Bar.class`). That, however, would require some additional changes to Her internals.

**Comment by zacharywelch** [comment] 2018-03-02 19:33
You could also place your Her models in a directory that's autoloaded or add that directory to the autoload path

**Comment by thornfoot** [comment] 2018-03-02 21:11
This has_many model is already in an auto-loaded directory. The issue is that sometimes autoloading would load the parent before the dependent class.

It also already had ``require 'bar'``, but after reading about Rails auto-loading, I wonder if require_dependency is the better directive for this. I like the Bar.class.name approach so I'll probably try that first.

As @blazingkin mentioned, this occurs at random. On my end it has been causing the test suite to fail in as much as 2/3 runs. Replacing the has_many eliminated the issue, but it's possible this is impacting others.
