### ISSUE TITLE
Changes not tracked properly on instance pulled from collection

### ISSUE THREAD

**Issue by derekprior** [remiprev/her#295] opened 2014-11-06 19:49 UTC
Consider:

``` ruby
u = User.all.first
u.changes
```

One would expect changes to be empty, but in fact every field is marked as changed. However:

``` ruby
u = User.find(1)
u.changes
```

Is empty as one would expect.

**Comment by paulvt** [comment] 2015-01-16 11:14
Indeed, clearing `@changed_attributes` is missing in several places.  I have added for `resource` in `Her::Model::Attributes.initialize_collection`, but this doesn't solve it for single resource associations.

**Comment by paulvt** [comment] 2015-01-16 12:33
Also added a clear to the `fetch` method of the various associations and now everything seems to be fine.  When I have time I will prepare a pull request.

**Comment by chewi** [comment] 2015-01-16 12:48
@paulvt, did you see my fix in #298? It should handle all cases.

**Comment by paulvt** [comment] 2015-01-16 13:02
I overlooked your pull request, cheers!
This is much more elegant than clearing it all over the place. (I am still getting to grips with the intricate structure of model, relation, association, proxy, etc.)

**Comment by kozze89** [comment] 2016-02-01 12:14
I can confirm that this is still an issue. Doesn't seem like @chewi's PR has been merged yet.

**Closed** 2018-04-13 00:44 UTC
